### ISSUE TITLE
Add repo contributors

### ISSUE THREAD

**Issue by beardaway** [auth0-community/auth0-winformsWPF-samples#14]

**Comment by beardaway** [comment]
@all-contributors please add @beardaway for maintenance, review

**Comment by beardaway** [comment]
@all-contributors please add @mehreencs87 for code

**Comment by beardaway** [comment]
@all-contributors please add @Amialc for code

**Comment by beardaway** [comment]
@all-contributors please add @jerriep  for code

**Comment by jerriep** [comment]
@beardaway Whoa, why are you adding me? I am not involved in Auth0 repositories anymore

**Comment by beardaway** [comment]
Hey there @jerriep! :) You're not but when you used to your contribution was significant, that's why :)

**Comment by jerriep** [comment]
@beardaway  Yeah, but this is going to become crazy because I contributed to and maintained a LOT of repos while I worked there. If you want to add me to the README, so be it, but please do not mention me in the issue and PR every time. I am not going to appreciate all those notifications. Please do it some other way.

**Comment by jerriep** [comment]
Or if you cannot do it another way, then do not add me to the list of contributors.

**Comment by beardaway** [comment]
Gotchya! Thanks a lot for the feedback!
